### ISSUE TITLE
Defaults have lower specificity than the preflight CSS

### ISSUE THREAD

**Issue by bill-kerr** [bill-kerr/tailwindcss-plugin-defaults#1]
Currently, styles defined in the preflight CSS have higher specificity than our default classes. This is because `:where()` automatically sets the specificity to 0.

I need to figure out a way to increase the specificity of the defaults while still remaining less specific than a class selector.

How to reproduce:

```html
<button class="d:bg-gray-100">I have a transparent background</button>
```

The button above will have a transparent background because of these lines in the preflight CSS:
```css
button,
[type='button'],
[type='reset'],
[type='submit'] {
  -webkit-appearance: button;
  /* 1 */
  background-color: transparent;
  /* 2 */
  background-image: none;
  /* 2 */
}
```
